import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#F9FAFB',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 12,
      backgroundColor: '#FFFFFF',
      borderBottomWidth: 1,
      borderBottomColor: '#E5E7EB',
    },
    backButton: {
      marginRight: 12,
    },
    headerInfo: {
      flex: 1,
    },
    matchTitle: {
      fontSize: 18,
      fontFamily: 'Inter-Bold',
      color: '#111827',
    },
    teamName: {
      fontSize: 12,
      color: '#6B7280',
      fontFamily: 'Inter-Regular',
    },
    scheduleButton: {
      padding: 8,
      borderRadius: 8,
      backgroundColor: '#FEF2F2',
      marginLeft: 8,
    },
    timeDisplayContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 12,
      backgroundColor: '#FFFFFF',
      borderBottomWidth: 1,
      borderBottomColor: '#F3F4F6',
    },
    timeInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    timeText: {
      fontSize: 16,
      fontFamily: 'Inter-Bold',
      color: '#111827',
    },
    quarterText: {
      fontSize: 12,
      fontFamily: 'Inter-Medium',
      color: '#6B7280',
    },
    scoreInfo: {
      alignItems: 'flex-end',
    },
    scoreText: {
      fontSize: 18,
      fontFamily: 'Inter-Bold',
      color: '#111827',
    },
    timeControl: {
      backgroundColor: '#FFFFFF',
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#E5E7EB',
    },
    playControls: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 12,
    },
    controlButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#F3F4F6',
      justifyContent: 'center',
      alignItems: 'center',
    },
    playButton: {
      backgroundColor: '#FF6B35',
      width: 48,
      height: 48,
      borderRadius: 24,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    loadingText: {
      fontSize: 16,
      color: '#6B7280',
      fontFamily: 'Inter-Medium',
    },
    substitutionBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#F0FDF4',
      paddingHorizontal: 20,
      paddingVertical: 12,
      gap: 8,
    },
    substitutionText: {
      flex: 1,
      fontSize: 13,
      color: '#16A34A',
      fontFamily: 'Inter-Medium',
    },
    cancelText: {
      fontSize: 13,
      color: '#DC2626',
      fontFamily: 'Inter-SemiBold',
    },
    viewModeContainer: {
      flexDirection: 'row',
      backgroundColor: '#FFFFFF',
      marginHorizontal: 20,
      marginVertical: 16,
      borderRadius: 12,
      padding: 4,
      borderWidth: 1,
      borderColor: '#E5E7EB',
    },
    viewModeButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
      borderRadius: 8,
      gap: 6,
    },
    activeViewMode: {
      backgroundColor: '#16A34A',
    },
    viewModeText: {
      fontSize: 13,
      fontFamily: 'Inter-SemiBold',
      color: '#6B7280',
    },
    activeViewModeText: {
      color: '#FFFFFF',
    },
    content: {
      flex: 1,
    },
    section: {
      paddingHorizontal: 20,
      paddingBottom: 20,
    },
    reserveSection: {
      paddingTop: 20,
      borderTopWidth: 1,
      borderTopColor: '#F3F4F6',
      marginTop: 20,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 12,
      gap: 8,
    },
    sectionTitle: {
      fontSize: 18,
      fontFamily: 'Inter-Bold',
      color: '#111827',
    },
    emptyContainer: {
      alignItems: 'center',
      paddingVertical: 40,
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#E5E7EB',
    },
    emptyTitle: {
      fontSize: 16,
      fontFamily: 'Inter-SemiBold',
      color: '#374151',
      marginTop: 12,
      marginBottom: 6,
    },
    emptySubtitle: {
      fontSize: 13,
      color: '#6B7280',
      textAlign: 'center',
      paddingHorizontal: 24,
      fontFamily: 'Inter-Regular',
    },
    emptyText: {
      fontSize: 14,
      color: '#6B7280',
      marginTop: 8,
      fontFamily: 'Inter-Medium',
    },
    // Timeline View Styles
    timelineContainer: {
      padding: 16,
    },
    activePlayersSection: {
      marginBottom: 24,
    },
    dualColumnContainer: {
      flexDirection: 'row',
      gap: 8,
    },
    liveColumn: {
      flex: 1,
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      overflow: 'hidden',
    },
    liveColumnHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: '#F9FAFB',
      borderBottomWidth: 1,
      borderBottomColor: '#E5E7EB',
      gap: 6,
    },
    liveColumnTitle: {
      fontSize: 14,
      fontFamily: 'Inter-SemiBold',
      color: '#111827',
    },
    livePlayersList: {
      padding: 8,
      gap: 4,
    },
    livePlayerCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFFFF',
      padding: 8,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      gap: 8,
    },
    benchPlayerCard: {
      backgroundColor: '#F9FAFB',
    },
    livePlayerInfo: {
      flex: 1,
    },
    livePlayerPosition: {
      fontSize: 10,
      fontFamily: 'Inter-SemiBold',
      color: '#6B7280',
      marginBottom: 4,
      marginTop: 2,
    },
    livePlayerDetails: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    livePlayerName: {
      fontSize: 12,
      fontFamily: 'Inter-SemiBold',
      color: '#111827',
    },
    livePlayerNumber: {
      fontSize: 10,
      fontFamily: 'Inter-Medium',
      color: '#6B7280',
    },
    livePlayerMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    reserveLabel: {
      fontSize: 8,
      fontFamily: 'Inter-Medium',
      color: '#9CA3AF',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginBottom: 2,
    },
    positionIndicator: {
      width: 10,
      height: 10,
      borderRadius: 5,
    },
    conditionDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
    },
    emptyBenchContainer: {
      alignItems: 'center',
      paddingVertical: 20,
      paddingHorizontal: 12,
    },
    emptyBenchText: {
      fontSize: 12,
      color: '#9CA3AF',
      marginTop: 6,
      fontFamily: 'Inter-Regular',
      textAlign: 'center',
    },
    upcomingSection: {
      marginBottom: 24,
    },
    upcomingList: {
      gap: 8,
    },
    upcomingCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#FFFBEB',
      padding: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#FED7AA',
      gap: 12,
    },
    upcomingTime: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    upcomingTimeText: {
      fontSize: 12,
      fontFamily: 'Inter-Bold',
      color: '#D97706',
    },
    upcomingDetails: {
      flex: 1,
    },
    upcomingPosition: {
      fontSize: 12,
      fontFamily: 'Inter-SemiBold',
      color: '#92400E',
      marginBottom: 2,
    },
    upcomingPlayer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    upcomingPlayerName: {
      fontSize: 14,
      fontFamily: 'Inter-SemiBold',
      color: '#111827',
    },
    upcomingPlayerAction: {
      fontSize: 12,
      fontFamily: 'Inter-Medium',
      color: '#D97706',
    },
    // Two-column layout styles
    twoColumnContainer: {
      flexDirection: 'row',
      paddingHorizontal: 20,
      paddingBottom: 20,
      gap: 12,
    },
    column: {
      flex: 1,
      backgroundColor: '#FFFFFF',
      borderRadius: 12,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      overflow: 'hidden',
    },
    columnHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      backgroundColor: '#F9FAFB',
      borderBottomWidth: 1,
      borderBottomColor: '#E5E7EB',
      gap: 8,
    },
    columnTitle: {
      fontSize: 14,
      fontFamily: 'Inter-SemiBold',
      color: '#111827',
      flex: 1,
    },
    countBadge: {
      backgroundColor: '#16A34A',
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 10,
      minWidth: 24,
      alignItems: 'center',
    },
    reserveCountBadge: {
      backgroundColor: '#6B7280',
    },
    countText: {
      fontSize: 11,
      fontFamily: 'Inter-Bold',
      color: '#FFFFFF',
    },
    reserveCountText: {
      color: '#FFFFFF',
    },
    emptyColumnContainer: {
      alignItems: 'center',
      paddingVertical: 32,
      paddingHorizontal: 16,
    },
    emptyColumnText: {
      fontSize: 12,
      color: '#9CA3AF',
      marginTop: 8,
      fontFamily: 'Inter-Regular',
      textAlign: 'center',
    },
    // Compact player card styles
    compactPlayersList: {
      padding: 8,
      gap: 4,
    },
    compactPlayerCard: {
      backgroundColor: '#FFFFFF',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      padding: 8,
    },
    selectedPlayerCard: {
      borderColor: '#10B981',
      backgroundColor: '#F0FDF4',
    },
    substitutingPlayerCard: {
      borderColor: '#FF6B35',
      backgroundColor: '#FEF2F2',
    },
    onFieldPlayerCard: {
      borderColor: '#10B981',
      backgroundColor: '#FFFFFF',
    },
    benchPlayerCard: {
      borderColor: '#E5E7EB',
      backgroundColor: '#F9FAFB',
    },
    playerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    playerNumberBadge: {
      width: 24,
      height: 24,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    playerNumberText: {
      fontSize: 9,
      fontFamily: 'Inter-Bold',
      color: '#FFFFFF',
    },
    playerInfo: {
      flex: 1,
      minWidth: 0,
    },
    playerName: {
      fontSize: 12,
      fontFamily: 'Inter-SemiBold',
      color: '#111827',
      marginBottom: 2,
    },
    playerMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    positionText: {
      fontSize: 9,
      fontFamily: 'Inter-Medium',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    metaSeparator: {
      fontSize: 8,
      color: '#D1D5DB',
      fontFamily: 'Inter-Regular',
    },
    timeText: {
      fontSize: 9,
      fontFamily: 'Inter-Regular',
      color: '#6B7280',
    },
    statBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 2,
    },
    statText: {
      fontSize: 8,
      fontFamily: 'Inter-Bold',
      color: '#10B981',
    },
    // Grid View Styles
    gridContainer: {
      padding: 16,
    },
    gridHeader: {
      flexDirection: 'row',
      backgroundColor: '#F9FAFB',
      borderRadius: 8,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: '#E5E7EB',
    },
    positionHeaderCell: {
      width: 120,
      padding: 12,
      justifyContent: 'center',
    },
    quarterHeaderCell: {
      flex: 1,
      padding: 12,
      alignItems: 'center',
      borderLeftWidth: 1,
      borderLeftColor: '#E5E7EB',
    },
    headerText: {
      fontSize: 12,
      fontFamily: 'Inter-Bold',
      color: '#374151',
      textAlign: 'center',
    },
    gridRow: {
      flexDirection: 'row',
      backgroundColor: '#FFFFFF',
      borderRadius: 8,
      marginBottom: 4,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      minHeight: 80,
    },
    positionCell: {
      width: 120,
      padding: 12,
      justifyContent: 'center',
      alignItems: 'center',
      borderRightWidth: 1,
      borderRightColor: '#F3F4F6',
    },
    positionName: {
      fontSize: 11,
      fontFamily: 'Inter-SemiBold',
      color: '#374151',
      textAlign: 'center',
      marginTop: 4,
    },
    quarterCell: {
      flex: 1,
      padding: 8,
      gap: 4,
      borderLeftWidth: 1,
      borderLeftColor: '#F3F4F6',
    },
    playerChip: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#F8FAFC',
      borderRadius: 8,
      padding: 6,
      gap: 8,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      marginBottom: 4,
    },
    playerNumber: {
      width: 24,
      height: 24,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
    },
    playerDetails: {
      flex: 1,
      minWidth: 0,
    },
    conditionIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 2,
    },
    conditionValue: {
      fontSize: 8,
      color: '#6B7280',
      fontFamily: 'Inter-Regular',
    },
    emptySlot: {
      padding: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptySlotText: {
      fontSize: 10,
      color: '#9CA3AF',
      fontFamily: 'Inter-Regular',
    },
  });